### ISSUE TITLE
Status? (28mar2021)

### ISSUE THREAD

**Issue by Jonta** [florianl/goNetViz#1]
Last commit is going on 3 years ago, and I can't get it to build

I'll take the time to write it up if there's a response. =)

**Comment by florianl** [comment]
Hi @Jonta 
Thanks for you interest!
With commit https://github.com/florianl/goNetViz/commit/0fefd4543d14f90c11f82ec8c0007495024f1f65 I have added the required changes so it can be build with a recent Go version easily. But as you already have noticed the code is untouched for some time now.

**Comment by Jonta** [comment]
```
$ go get -u github.com/florianl/goNetViz
# github.com/google/gopacket/pcap
../../go/src/github.com/google/gopacket/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.
```

**Comment by florianl** [comment]
Closing this issue for now. Please don't hesitate to reopen it or open a new issue if there a further issues.
